# Generated by Django 5.0.3 on 2024-06-06 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testschedule',
            name='build_name',
        ),
        migrations.RemoveField(
            model_name='testschedule',
            name='config_name',
        ),
        migrations.RemoveField(
            model_name='testschedule',
            name='project_name',
        ),
        migrations.AddField(
            model_name='testschedule',
            name='serial_number',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='board.board'),
            preserve_default=False,
        ),
    ]
