# Generated by Django 5.0.3 on 2024-07-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_board_status_alter_testrecord_result_errorrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorrecord',
            name='fail_type',
        ),
    ]
