# Generated by Django 5.0.3 on 2024-07-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_errorrecord_cp_nums_errorrecord_radar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='subprotject_name',
            new_name='subproject_name',
        ),
    ]
