# Generated by Django 5.0.3 on 2024-07-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_rename_configration_board_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorrecord',
            name='fail_picture',
            field=models.ImageField(blank=True, null=True, upload_to='failures/%Y/%m/%d/'),
        ),
    ]
