# Generated by Django 5.0.3 on 2024-07-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_board_if_overdue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrecord',
            name='site',
        ),
        migrations.AddField(
            model_name='board',
            name='site',
            field=models.CharField(default='FXLH', max_length=20),
        ),
        migrations.AlterField(
            model_name='board',
            name='status',
            field=models.CharField(choices=[('testing', 'testing'), ('pause', 'pause'), ('damage', 'damage'), ('cancel', 'cancel'), ('CS', 'CS'), ('archived', 'archived')], default='testing', max_length=10),
        ),
    ]
